spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8912

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments